### ISSUE TITLE
Endless loop using the move command

### ISSUE THREAD

**Issue by thomas-hilaire** [jmapio/jmap-js#3]
Hello,

I'm trying to code a webmail using your library but I encounter an issue when I try to implement the "move" (it seems that I've the same issue with marking a message read/unread).

1) At the beginning the message status is 2 (READY)

2) I'm using the command suggested in the readme: 

```
JMAP.mail.move(messages, JMAP.mail.systemMailboxIds.get('trash'), null);
```

3) The message deletion is well sent.

The query looks like:

```
0: ["setMessages",…]   ## The expected command is there 
1: ["getMailboxes",…]
2: ["getThreads", {ids: ["bcb97880f9f80d9f90c38e976a5045fb4c2830da"], fetchMessages: true,…}, "2"]
```

and the response (from the jmap-perl proxy) looks like:

```
0: ["messagesSet",…]
1: ["mailboxes", {accountId: "c3147952-4d8c-11e5-9396-0242ac110067",…}, "1"]
2: ["threads", {accountId: "c3147952-4d8c-11e5-9396-0242ac110067",…}, "2"]
3: ["messages", {accountId: "c3147952-4d8c-11e5-9396-0242ac110067",…}, "2"]
```

4) As there is a "messages" section into, the callback "JMAP.mail.handle( Message, ...#messages)" defined in "jmap-js/source/mail/Message.js" is applied. Then it tells to the store that the message has been updated with:

```
this.get( 'store' ).sourceDidFetchPartialRecords( Message, updates );
```

5) in this method, the lib has a status of 50 for this message so it wants to fetch its data again:

```
        // If OBSOLETE, the record may have changed since the fetch was
        // initiated. Since we don't want to overwrite any preemptive
        // changes, ignore this data and fetch it again.
        // Similarly if the record is committing, we don't know for sure
        // what state the update was applied on top of, so fetch again
        // to be sure.
        if ( status & (COMMITTING|OBSOLETE) ) {
            this.setStatus( storeKey, status & ~LOADING );
            this.fetchData( storeKey );
            continue;
        }
```

So, a new "getMessages" is sent to the JMAP server. The new query looks like:

```
[["getMessages", {ids: ["88dcb8982a31ac3a0ae33513c6a15e4b36934a28"],…}, "0"]]
```

and the response:

```
["messages", {accountId: "c3147952-4d8c-11e5-9396-0242ac110067",…}, "0"]
```

6) So the code goes back to the "step 4" when the response is received. It makes an endless loop ..

Do you understand what I'm doing wrong ? Any clue ?

Thanks!

**Comment by neilj** [comment]
Status 50 means it's still got the `COMMITTING` bit (`32`) set, so it sounds like something went wrong with the messagesSet response. Since the `COMMITTING` bit never gets cleared, it gets stuck in the loop as you described. As you omitted the content of the messagesSet response, I'm not quite sure what was going on (and it would certainly be easier to debug with a live copy of the code anyway). It could be a bogus response from the JMAP-Perl library.

Have you tried doing the move on the [hosted version](https://proxy.jmap.io) of the [demo webmail](https://github.com/jmapio/jmap-demo-webmail)? This uses the same library underneath – have a look at the data exchanges there and hopefully the difference will become apparent.

**Comment by thomas-hilaire** [comment]
Hello @neilj, thanks for your reply!

I've compared exchanges between my app and your demo app, there are some differences but I can't find out what's the problematic thing. 
Divergencies that I've noted:

1) I've a "getThreads" section beside "setMessages" in the performed request, there is not in the demo

--> so there are "threads" and "messages" properties in the response given by the jmap-proxy

2) After getting the "setMessages" response, in both apps the jmap-js lib is performing a second request.
- For the demo app, there is a "getMessageListUpdates" section which is not send with my app
- For my app, there is a "getMessages" section which is not send with your demo app

--> I'm getting a "messages" section in my response, a "messageListUpdates" in the demo response.
I guess that this difference comes because I'm observing this email for changes with the code below. Can it be the issue ?

```
  var record = JMAP.store.getRecord(JMAP.Message, emailId);
  record.addObserverForKey('*', request, 'callback');
```

3) The jmap-js starts its endless loop at this point for my app by doing the "getMessages" request.
In the demo, I guess that the COMMIT is well done so it doesn't do anymore request.

As I'm not fluent as you about JMAP talking, I'm joining requests and responses that I've captured.
May be that you'll find out the annoying thing that makes this endless loop?
- with my custom app: https://gist.github.com/thomas-hilaire/0f5143db28f10df843e4
- with the demo app: https://gist.github.com/thomas-hilaire/dcd0306e6860364fe149

Thanks again, regards,
Thomas

**Comment by neilj** [comment]
Thanks for the logs; the problem is clearly here:

```
[
  "messagesSet",
  {
     "accountId" : "97d3e0d6-517c-11e5-86a6-0242ac11006f",
     "created" : {},
     "deleted" : "",
     "newState" : "29",
     "notCreated" : {},
     "notDeleted" : null,
     "notUpdated" : null,
     "oldState" : null,
     "updated" : ""
  },
  "0"
]
```

This response from the server is bogus: `updated` and `destroyed` (`deleted` is even the wrong name!) should be objects, not strings, and the id of the message you tried to modify MUST be in either `updated` or `notUpdated`. So since it never gets a response from the server, the library presumes it's still committing, so gets into this loop where it's waiting for the commit to finish.

Are you using the hosted version of the proxy, at https://proxy.jmap.io? Or are you hosting it yourself? If the latter, make sure you have the latest version of the proxy code.

The good news is it doesn't look like there's anything wrong with your code! The bad news is this is probably a bug in the [JMAP Proxy](https://github.com/jmapio/jmap-perl) – please file a bug there and hopefully @brong will take a look and fix it.
